import { TaxonomyItem } from "./types";

// DRAFT for team review. Ids are permanent once shipped; see TaxonomyItem.
export const SKILLS = [
  { id: "python", label: "Python" },
  { id: "java", label: "Java" },
  { id: "c-cpp", label: "C / C++" },
  { id: "javascript-typescript", label: "JavaScript / TypeScript" },
  { id: "sql", label: "SQL" },
  { id: "functional-programming", label: "Functional Programming" },
  { id: "algorithms", label: "Data Structures & Algorithms" },
  { id: "systems-programming", label: "Systems Programming" },
  { id: "operating-systems", label: "Operating Systems" },
  { id: "networking", label: "Computer Networks" },
  { id: "distributed-systems", label: "Distributed Systems" },
  { id: "databases", label: "Databases" },
  { id: "web-development", label: "Web Development" },
  { id: "mobile-development", label: "Mobile Development" },
  { id: "cloud-devops", label: "Cloud & DevOps" },
  { id: "machine-learning", label: "Machine Learning" },
  { id: "deep-learning", label: "Deep Learning" },
  { id: "nlp", label: "Natural Language Processing" },
  { id: "computer-vision", label: "Computer Vision" },
  { id: "reinforcement-learning", label: "Reinforcement Learning" },
  { id: "statistics", label: "Statistics" },
  { id: "probability", label: "Probability" },
  { id: "linear-algebra", label: "Linear Algebra" },
  { id: "optimization", label: "Optimization" },
  { id: "data-visualization", label: "Data Visualization" },
  { id: "security-fundamentals", label: "Security Fundamentals" },
  { id: "cryptography", label: "Cryptography" },
  { id: "computer-architecture", label: "Computer Architecture" },
  { id: "embedded-systems", label: "Embedded Systems" },
  { id: "controls", label: "Controls & Robotics" },
  { id: "ui-ux-design", label: "UI / UX Design" },
  { id: "user-research", label: "User Research" },
  { id: "product-strategy", label: "Product Strategy" },
  { id: "financial-modeling", label: "Financial Modeling" },
  { id: "technical-writing", label: "Technical Writing & Communication" },
  { id: "leadership", label: "Leadership & Teamwork" },
] as const satisfies readonly TaxonomyItem[];

export type SkillID = (typeof SKILLS)[number]["id"];
